/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { FunctionalComponent } from "@stencil/core";
import { DemoData } from "./global/demo";
import { MyComponentViewProps } from "./components/sqh-my-component/sqh-my-component-view";
export namespace Components {
    interface SqhHookStoryContainer {
        "hookStory": FunctionalComponent;
    }
    interface SqhMyComponent {
        /**
          * @undocumented 
          * @uiType object
         */
        "demoData"?: DemoData<MyComponentViewProps>;
        /**
          * @uiName Text to display with user name
         */
        "myTitle": string;
    }
    interface SqhStencilbook {
    }
}
declare global {
    interface HTMLSqhHookStoryContainerElement extends Components.SqhHookStoryContainer, HTMLStencilElement {
    }
    var HTMLSqhHookStoryContainerElement: {
        prototype: HTMLSqhHookStoryContainerElement;
        new (): HTMLSqhHookStoryContainerElement;
    };
    interface HTMLSqhMyComponentElement extends Components.SqhMyComponent, HTMLStencilElement {
    }
    var HTMLSqhMyComponentElement: {
        prototype: HTMLSqhMyComponentElement;
        new (): HTMLSqhMyComponentElement;
    };
    interface HTMLSqhStencilbookElement extends Components.SqhStencilbook, HTMLStencilElement {
    }
    var HTMLSqhStencilbookElement: {
        prototype: HTMLSqhStencilbookElement;
        new (): HTMLSqhStencilbookElement;
    };
    interface HTMLElementTagNameMap {
        "sqh-hook-story-container": HTMLSqhHookStoryContainerElement;
        "sqh-my-component": HTMLSqhMyComponentElement;
        "sqh-stencilbook": HTMLSqhStencilbookElement;
    }
}
declare namespace LocalJSX {
    interface SqhHookStoryContainer {
        "hookStory"?: FunctionalComponent;
    }
    interface SqhMyComponent {
        /**
          * @undocumented 
          * @uiType object
         */
        "demoData"?: DemoData<MyComponentViewProps>;
        /**
          * @uiName Text to display with user name
         */
        "myTitle"?: string;
    }
    interface SqhStencilbook {
    }
    interface IntrinsicElements {
        "sqh-hook-story-container": SqhHookStoryContainer;
        "sqh-my-component": SqhMyComponent;
        "sqh-stencilbook": SqhStencilbook;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sqh-hook-story-container": LocalJSX.SqhHookStoryContainer & JSXBase.HTMLAttributes<HTMLSqhHookStoryContainerElement>;
            "sqh-my-component": LocalJSX.SqhMyComponent & JSXBase.HTMLAttributes<HTMLSqhMyComponentElement>;
            "sqh-stencilbook": LocalJSX.SqhStencilbook & JSXBase.HTMLAttributes<HTMLSqhStencilbookElement>;
        }
    }
}
